In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

In [7]:
s = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 

In [8]:
s

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [25]:
s[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [27]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]]) 
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [28]:
arrayOne

array([[ 5,  6,  9],
       [21, 18, 27]])

In [29]:
arrayTwo

array([[15, 33, 24],
       [ 4,  7,  1]])

In [32]:
arrayThree=arrayOne+arrayTwo


In [33]:
arrayThree

array([[20, 39, 33],
       [25, 25, 28]])

In [34]:
np.square(arrayThree)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [42]:
k = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [43]:
k

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [45]:
m = k [ :, k[1].argsort()]

In [46]:
m

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [47]:
p=k[k[:, 1].argsort()]

In [48]:
p

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [52]:
print(p)

[[82 22 12]
 [34 43 73]
 [53 94 66]]
